"""Remove address from UserProfile

Revision ID: 5cbd1ca91357
Revises: bee7b446865d
Create Date: 2025-12-01 16:26:07.134375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cbd1ca91357'
down_revision = 'bee7b446865d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=300), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
