"""Add volume_id to Book model

Revision ID: bee7b446865d
Revises: 
Create Date: 2025-12-01 14:22:40.775179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bee7b446865d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('volume_id', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['volume_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('volume_id')

    # ### end Alembic commands ###
